spring:
  application:
    name: user
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.redisson.spring.starter.RedissonAutoConfiguration
  datasource:
    ## 参考:https://github.com/drtrang/druid-spring-boot
    ## schema: classpath:import.sql
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.p6spy.engine.spy.P6SpyDriver
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      filters: stat,wall,slf4j
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      async-init: true
      max-open-prepared-statements: 20
      time-between-eviction-runs-millis: 60000
      validation-query-timeout: 30
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-return: false
      test-on-borrow: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: britton
        login-password: britton
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
  profiles:
    active: dev
  cache:
    type: none

#mybatis
mybatis-plus:
  mapper-locations: classpath:/mappers/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.geoxus.com.geoxus.core.framework.entity;com.geoxus.modules.*.entity
  typeEnumsPackage: com.geoxus.com.geoxus.core.framework.entity.enums;com.geoxus.modules.*.entity.enums
  typeHandlersPackage: com.geoxus.com.geoxus.core.framework.handlers
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      #数据库大写下划线转换
      capital-mode: true
      #逻辑删除配置
      logic-delete-field: is_deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      column-format: "%s"
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    aggressive-lazy-loading: false
    lazy-loading-enabled: false
    
dubbo:
  registry:
    #address: nacos://127.0.0.1:8848
    address: zookeeper://127.0.0.1:2181
  application:
    name: ${spring.application.name}
    protocol: dubbo
  protocol:
    name: dubbo
  scan:
    base-packages: cn.gaple.user

nacos:
  config:
    server-addr: 47.108.213.62:8848
    auto-refresh: true
    bootstrap:
      enable: true  # 需要配置data-id 和 type  否则会报错
    data-id: britton.test.yml
    type: yaml
    namespace: d937e439-cac3-4004-8f13-b88fbe0bcd56  # 需要设置  否则不能自动更新
