nacos:
  config:
    server-addr: 192.168.1.245:8848
    auto-refresh: true
    bootstrap:
      enable: true  # 需要配置data-id 和 type  否则会报错
    data-id: application-aggregate.yml
    type: yaml
    namespace: fa8dc755-ba13-4fa3-b926-186a56a7bf29  # 需要设置  否则不能自动更新
