nacos:
  config:
    server-addr: 192.168.1.245:8848
    auto-refresh: true
    bootstrap:
      enable: true  # 需要配置data-id 和 type  否则会报错
    data-id: application.yml
    type: yaml
    namespace: d3b4c585-ed74-4a95-a9df-75c72ebc10bb  # 需要设置  否则不能自动更新
