server:
  port: 3344
spring:
  application:
    name: user
dubbo:
  registry:
    #address: nacos://127.0.0.1:8848
    address: zookeeper://127.0.0.1:2181
  application:
    name: ${spring.application.name}
    protocol: dubbo
  protocol:
    name: dubbo
  scan:
    base-packages: cn.gaple.user

nacos:
  config:
    server-addr: 47.108.213.62:8848
    auto-refresh: true
    bootstrap:
      enable: true  # 需要配置data-id 和 type  否则会报错
    data-id: britton.test.yml
    type: yaml
    namespace: d937e439-cac3-4004-8f13-b88fbe0bcd56  # 需要设置  否则不能自动更新

