redisson:
  config:
    testMap:
      ttl: 100000
      maxIdleTime: 10000000
      maxSize: 10000
    brtCache:
      ttl: 600000
      maxIdleTime: 10000000
      maxSize: 1000
    __DEFAULT__:
      ttl: 600000
      maxIdleTime: 100000000
      maxSize: 1000